app_name = "SodKat"
version = "1.0.0"

[[keys]]
key = "C a"
scope = ["photoshop.exe"]
function = "do_something_in_photoshop"

[[keys]]
key = "C a"
scope = ["code.exe"]
function = "do something in code editor"
